name: Update webring status

inputs:
  webring-input:
    default: webring.json
  status-output:
    default: "" # webring.json -> webring.status.json
  scrape-for-webring-src:
    default: ""
    description: |
      If non-empty, all sites will be scraped for the webring source.
      This is used to check for the missingWebring property.
  scrape-timeout:
    default: 10000
    description: |
      The timeout for scraping a site, in milliseconds.
      Only used if scrape-for-webring-src is non-empty.
  commit:
    default: false
  commit-message:
    default: "Update webring status file"

runs:
  using: composite
  steps:
    - name: Initialize environment
      id: env
      shell: bash
      run: |
        echo "root=${ACTION_PATH%%.github*}" >> $GITHUB_OUTPUT
        echo "NIXPKGS_ALLOW_UNFREE=1" >> $GITHUB_ENV
      env:
        ACTION_PATH: ${{ github.action_path }}

    - uses: diamondburned/cache-install@main
      with:
        key-prefix: nix-libwebring-health-check-
        shell-file: ${{ steps.env.outputs.root }}/cmd/health-check-v2/shell.nix
        auto-optimise: true

    - run: |
        ${{ steps.env.outputs.root }}/cmd/health-check-v2/main.ts \
          -i "$webring_input" \
          -o "$status_output" \
          --scrape-for-webring-src "$scrape_for_webring_src" \
          --scrape-timeout "$scrape_timeout"
      shell: bash
      env:
        webring_input: ${{ inputs.webring-input }}
        status_output: ${{ inputs.status-output }}
        scrape_for_webring_src: ${{ inputs.scrape-for-webring-src }}
        scrape_timeout: ${{ inputs.scrape-timeout }}

    - uses: stefanzweifel/git-auto-commit-action@v4
      if: ${{ inputs.commit }}
      with:
        commit_message: ${{ inputs.commit-message }}
