name: Update webring status

inputs:
  webring-input:
    default: webring.json
  status-output:
    default: "" # webring.json -> webring.status.json
  commit:
    default: false
  commit-message:
    default: "Update webring status file"

runs:
  using: composite
  steps:
    - name: Initialize environment
      id: env
      shell: bash
      run: |
        echo "root=${ACTION_PATH%%.github*}" >> $GITHUB_OUTPUT
      env:
        ACTION_PATH: ${{ github.action_path }}

    - name: Install Nix dependencies
      uses: diamondburned/cache-install@main
      with:
        shell-file: ${{ steps.env.outputs.root }}/shell.nix
        auto-optimise: true

    - name: Run health check
      run: |
        cd ${{ steps.env.outputs.root }}
        ./cmd/health-check.ts \
          -i ${{ inputs.webring-input }} \
          -o ${{ inputs.status-output }}
      shell: bash

    - name: Commit changes
      if: ${{ inputs.commit }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ inputs.commit-message }}

    - name: Restore current directory
      run: popd
      shell: bash
