name: Update dist

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  dist:
    name: Update dist
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Pull dist artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: dist
          commit_message: |
            Build to dist

            Built from commit ${{ github.sha }}
