name: Build to Nightly

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Update Nightly
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pull dist artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: nightly
          file_pattern: dist
          add_options: --force
          push_options: --force
          skip_fetch: true
          skip_checkout: true
          create_branch: true
          commit_message: Build nightly to ${{ github.sha }}
